from kNN import calc_with_knearestNeighbour
from randomforestregressor import calc_with_RandomForestRegressor
from randomforestclassifier import calc_with_RandomForestClassifier



#calc_with_knearestNeighbour()
#calc_with_RandomForestRegressor()
#calc_with_RandomForestClassifier()
